

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CasgemPortfolio.Models.Entities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CasgemPortfolioEntities4 : DbContext
{
    public CasgemPortfolioEntities4()
        : base("name=CasgemPortfolioEntities4")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<TblAdmin> TblAdmin { get; set; }

    public virtual DbSet<TblContact> TblContact { get; set; }

    public virtual DbSet<TblDepartment> TblDepartment { get; set; }

    public virtual DbSet<TblEmployee> TblEmployee { get; set; }

    public virtual DbSet<TblFeature> TblFeature { get; set; }

    public virtual DbSet<TblMessage> TblMessage { get; set; }

    public virtual DbSet<TblProject> TblProject { get; set; }

    public virtual DbSet<TblResume> TblResume { get; set; }

    public virtual DbSet<TblService> TblService { get; set; }

    public virtual DbSet<TblSkill> TblSkill { get; set; }

    public virtual DbSet<TblSkillDegree> TblSkillDegree { get; set; }

    public virtual DbSet<TblSkillDescription> TblSkillDescription { get; set; }

    public virtual DbSet<TblSocial> TblSocial { get; set; }

    public virtual DbSet<TblTestimonial> TblTestimonial { get; set; }

    public virtual DbSet<TblVideo> TblVideo { get; set; }

    public virtual DbSet<TblWhoAmI> TblWhoAmI { get; set; }

    public virtual DbSet<TblAchievement> TblAchievement { get; set; }

}

}

