
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CasgemPortfolio.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class TblContact
{

    public int ContactId { get; set; }

    public string Phone { get; set; }

    public string Mail { get; set; }

    public string Adrress { get; set; }

    public string NameSurname { get; set; }

    public string Age { get; set; }

    public string City { get; set; }

}

}
