
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CasgemPortfolio.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class TblSocial
{

    public int SocialMediaId { get; set; }

    public string SocialMediaName { get; set; }

    public string SocialMediaIcon { get; set; }

    public string SocialMediaUrl { get; set; }

}

}
