
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CasgemPortfolio.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class TblTestimonial
{

    public int TestimonialId { get; set; }

    public string NameSurname { get; set; }

    public string Country { get; set; }

    public string TestimonialContent { get; set; }

    public string ImageURL { get; set; }

}

}
