
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CasgemPortfolio.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class TblWhoAmI
{

    public int WhoId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string CvLink { get; set; }

}

}
